package br.edu.ifpb.gestaobibliotecadigital.views.components;

public class PesquisarPanel extends javax.swing.JPanel {

    public final UpdateObserver events = new UpdateObserver();

    public PesquisarPanel() {
        initComponents();
        initCaixaPesquisaEvents();
    }

    /**
     * Retorna o texto da caixa de pesquisa
     *
     * @return Texto da caixa de pesquisa
     */
    public String getText() {
        return caixaDePesquisa.getText();
    }

    /**
     * Configura eventos para a caixa de pesquisa
     */
    private void initCaixaPesquisaEvents() {
        // Observa alterações na caixa de pesquisa
        caixaDePesquisa.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                events.emit();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                events.emit();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                // Ignora
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisaLabel = new javax.swing.JLabel();
        caixaDePesquisa = new javax.swing.JTextField();

        pesquisaLabel.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(caixaDePesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pesquisaLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pesquisaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caixaDePesquisa;
    private javax.swing.JLabel pesquisaLabel;
    // End of variables declaration//GEN-END:variables
}
