package br.edu.ifpb.gestaobibliotecadigital.views.components;

import br.edu.ifpb.gestaobibliotecadigital.models.usuarios.Usuario;
import br.edu.ifpb.gestaobibliotecadigital.session.UserSessionManager;

public class UsuarioPanel extends javax.swing.JPanel {

    private final Usuario usuarioLogado = UserSessionManager.getInstance().getUsuarioLogado();

    public UsuarioPanel() {
        initComponents();
        initDadosUsuario();
    }

    /**
     * Exibe os dados do usuário
     */
    private void initDadosUsuario() {
        if (usuarioLogado != null) {
            nomeUsuario.setText(usuarioLogado.getNome());
            tipoUsuario.setText(usuarioLogado.getTipo());
        } else {
            nomeUsuario.setText("Anônimo");
            tipoUsuario.setText("Não está logado");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeUsuario = new javax.swing.JLabel();
        tipoUsuario = new javax.swing.JLabel();

        nomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nomeUsuario.setText("Nome do Usuário");

        tipoUsuario.setText("Tipo do Usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipoUsuario, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nomeUsuario)
                .addGap(0, 0, 0)
                .addComponent(tipoUsuario))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomeUsuario;
    private javax.swing.JLabel tipoUsuario;
    // End of variables declaration//GEN-END:variables
}
