package br.edu.ifpb.gestaobibliotecadigital.views.usuarios;

import br.edu.ifpb.gestaobibliotecadigital.models.usuarios.Usuario;

public class DetalhesUsuario extends javax.swing.JPanel {

    private Usuario usuario;

    public DetalhesUsuario() {
        initComponents();
        setUsuario(null);
    }

    /**
     * Atualiza o usuário selecionado
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;

        if (usuario == null) {
            nomeUsuario.setText(" ");
        } else {
            nomeUsuario.setText(usuario.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioBorder = new javax.swing.JPanel();
        nomeUsuario = new javax.swing.JLabel();

        usuarioBorder.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));

        nomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeUsuario.setText("Nome do usuário");

        javax.swing.GroupLayout usuarioBorderLayout = new javax.swing.GroupLayout(usuarioBorder);
        usuarioBorder.setLayout(usuarioBorderLayout);
        usuarioBorderLayout.setHorizontalGroup(
            usuarioBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        usuarioBorderLayout.setVerticalGroup(
            usuarioBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioBorderLayout.createSequentialGroup()
                .addComponent(nomeUsuario)
                .addGap(0, 118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomeUsuario;
    private javax.swing.JPanel usuarioBorder;
    // End of variables declaration//GEN-END:variables

}
