package br.edu.ifpb.gestaobibliotecadigital.views.emprestimos;

import br.edu.ifpb.gestaobibliotecadigital.models.emprestimos.Emprestimo;
import br.edu.ifpb.gestaobibliotecadigital.repositories.EmprestimoRepository;
import br.edu.ifpb.gestaobibliotecadigital.views.components.UpdateObserver;
import javax.swing.JOptionPane;

public class AcoesEmprestimo extends javax.swing.JPanel {

    private Emprestimo emprestimo;
    public final UpdateObserver events = new UpdateObserver();

    // TODO: mudar para controller
    private final EmprestimoRepository emprestimoRepository = EmprestimoRepository.getInstance();

    public AcoesEmprestimo() {
        initComponents();
    }

    /**
     * Atualiza o empréstimo selecionado
     */
    public void setEmprestimo(Emprestimo emprestimo) {
        this.emprestimo = emprestimo;

        remover.setEnabled(emprestimo != null);
        devolver.setEnabled(emprestimo != null && !emprestimo.foiDevolvido());
        multaPaga.setEnabled(emprestimo != null && emprestimo.foiDevolvido() && emprestimo.temMultaPendente());
        renovar.setEnabled(emprestimo != null && emprestimo.podeRenovar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atualizar = new javax.swing.JButton();
        adicionar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        devolver = new javax.swing.JButton();
        renovar = new javax.swing.JButton();
        multaPaga = new javax.swing.JButton();

        atualizar.setText("Atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        adicionar.setText("Adicionar");

        remover.setText("Remover");
        remover.setEnabled(false);
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        devolver.setText("Devolver");
        devolver.setEnabled(false);

        renovar.setText("Renovar");
        renovar.setEnabled(false);

        multaPaga.setText("Multa paga");
        multaPaga.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(devolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(renovar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multaPaga))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adicionar)
                .addComponent(remover)
                .addComponent(renovar)
                .addComponent(multaPaga)
                .addComponent(devolver)
                .addComponent(atualizar))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        events.emit();
    }//GEN-LAST:event_atualizarActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed

        int resposta = JOptionPane.showConfirmDialog(
                null,
                "Deseja remover?",
                "Remove?",
                JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {
            emprestimoRepository.excluir(emprestimo);
            events.emit();
        }
    }//GEN-LAST:event_removerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton devolver;
    private javax.swing.JButton multaPaga;
    private javax.swing.JButton remover;
    private javax.swing.JButton renovar;
    // End of variables declaration//GEN-END:variables
}
