package br.edu.ifpb.gestaobibliotecadigital.views.emprestimos;

import br.edu.ifpb.gestaobibliotecadigital.models.emprestimos.Emprestimo;
import br.edu.ifpb.gestaobibliotecadigital.utils.Formatter;
import java.time.LocalDateTime;

public class DetalhesEmprestimo extends javax.swing.JPanel {

    private Emprestimo emprestimo;

    public DetalhesEmprestimo() {
        initComponents();
        setEmprestimo(null);
    }

    /**
     * Atualiza o empréstimo selecionado
     */
    public void setEmprestimo(Emprestimo emprestimo) {
        this.emprestimo = emprestimo;

        if (emprestimo == null) {
            titulo.setText("Selecione um Empréstimo...");
            dataDoEmprestimo.setText(" ");
            devolvidoEm.setText(" ");
            multa.setText(" ");
            renovacoesRealizadas.setText(" ");
            renovacoesRestantes.setText(" ");
            ultimaRenovacao.setText(" ");
            return;
        }

        LocalDateTime devolvido = emprestimo.getDataDevolvido();
        double multaValor = emprestimo.getMulta();

        if (emprestimo.estaAtrasado()) {
            titulo.setText("Livro Atrasado");
        } else if (emprestimo.foiDevolvido()) {
            titulo.setText("Livro Devolvido");
        } else if (emprestimo.temMultaPendente()) {
            titulo.setText("Pagamento da Multa Pendente");
        } else {
            titulo.setText("Livro Emprestado");
        }

        dataDoEmprestimo.setText(Formatter.of(emprestimo.getDataEmprestimo()).toString());
        devolvidoEm.setText(devolvido == null ? "Não" : Formatter.of(devolvido).toString());
        multa.setText(multaValor > 0 ? "R$ " + Formatter.of(multaValor).toString() : "Não");
        renovacoesRealizadas.setText(Integer.toString(emprestimo.getQuantidadeRenovacoes()));
        renovacoesRestantes.setText(Integer.toString(emprestimo.getQuantidadeRenovacoesRestantes()));
        ultimaRenovacao.setText(Formatter.of(emprestimo.getDataUltimaRenovacao()).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detalhesEmprestimo = new javax.swing.JPanel();
        dataDoEmprestimoLabel = new javax.swing.JLabel();
        devolvidoEmLabel = new javax.swing.JLabel();
        multaLabel = new javax.swing.JLabel();
        renovacoesRealizadasLabel = new javax.swing.JLabel();
        renovacoesRestantesLabel = new javax.swing.JLabel();
        ultimaRenovacaoLabel = new javax.swing.JLabel();
        dataDoEmprestimo = new javax.swing.JLabel();
        devolvidoEm = new javax.swing.JLabel();
        multa = new javax.swing.JLabel();
        renovacoesRealizadas = new javax.swing.JLabel();
        renovacoesRestantes = new javax.swing.JLabel();
        ultimaRenovacao = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        detalhesEmprestimo.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do Empréstimo"));

        dataDoEmprestimoLabel.setText("Data do emprésimo:");

        devolvidoEmLabel.setText("Devolvido em:");

        multaLabel.setText("Multa:");

        renovacoesRealizadasLabel.setText("Renovações realizadas:");

        renovacoesRestantesLabel.setText("Renovações restantes:");

        ultimaRenovacaoLabel.setText("Última renovação:");

        dataDoEmprestimo.setText("00/00/00 00:00:00");

        devolvidoEm.setText("00/00/00 00:00:00");

        multa.setText("R$ 0,00");

        renovacoesRealizadas.setText("0");

        renovacoesRestantes.setText("0");

        ultimaRenovacao.setText("00/00/00 00:00:00");

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo.setText("Status do Empréstimo");

        javax.swing.GroupLayout detalhesEmprestimoLayout = new javax.swing.GroupLayout(detalhesEmprestimo);
        detalhesEmprestimo.setLayout(detalhesEmprestimoLayout);
        detalhesEmprestimoLayout.setHorizontalGroup(
            detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataDoEmprestimoLabel)
                            .addComponent(devolvidoEmLabel)
                            .addComponent(multaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataDoEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(devolvidoEm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                                .addComponent(renovacoesRestantesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(renovacoesRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                                    .addComponent(renovacoesRealizadasLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(renovacoesRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                                    .addComponent(ultimaRenovacaoLabel)
                                    .addGap(32, 32, 32)
                                    .addComponent(ultimaRenovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        detalhesEmprestimoLayout.setVerticalGroup(
            detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(renovacoesRealizadasLabel)
                            .addComponent(renovacoesRealizadas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(renovacoesRestantesLabel)
                            .addComponent(renovacoesRestantes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ultimaRenovacaoLabel)
                            .addComponent(ultimaRenovacao)))
                    .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataDoEmprestimoLabel)
                            .addComponent(dataDoEmprestimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(devolvidoEmLabel)
                            .addComponent(devolvidoEm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multaLabel)
                            .addComponent(multa))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detalhesEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(detalhesEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataDoEmprestimo;
    private javax.swing.JLabel dataDoEmprestimoLabel;
    private javax.swing.JPanel detalhesEmprestimo;
    private javax.swing.JLabel devolvidoEm;
    private javax.swing.JLabel devolvidoEmLabel;
    private javax.swing.JLabel multa;
    private javax.swing.JLabel multaLabel;
    private javax.swing.JLabel renovacoesRealizadas;
    private javax.swing.JLabel renovacoesRealizadasLabel;
    private javax.swing.JLabel renovacoesRestantes;
    private javax.swing.JLabel renovacoesRestantesLabel;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel ultimaRenovacao;
    private javax.swing.JLabel ultimaRenovacaoLabel;
    // End of variables declaration//GEN-END:variables
}
