package br.edu.ifpb.gestaobibliotecadigital.views.emprestimos;

import br.edu.ifpb.gestaobibliotecadigital.filters.EmprestimoFiltro;
import br.edu.ifpb.gestaobibliotecadigital.views.components.UpdateObserver;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JTextField;

public class PesquisaAvancadaEmprestimos extends javax.swing.JPanel {

    public final UpdateObserver events = new UpdateObserver();
    private EmprestimoFiltro filtro = new EmprestimoFiltro();

    public PesquisaAvancadaEmprestimos() {
        initComponents();
        initEnterPress();
    }

    /**
     * Retorna o filtro atual
     */
    public EmprestimoFiltro getFiltro() {
        return filtro;
    }

    /**
     * Configura para quando pressionar enter em qualquer TextField, executar a pesquisa
     */
    private void initEnterPress() {
        ActionListener enter = evt -> {
            pesquisarActionPerformed(evt);
        };

        for (Component component : getComponents()) {
            if (component instanceof JTextField) {
                ((JTextField) component).addActionListener(enter);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        tituloLivroLabel = new javax.swing.JLabel();
        tituloLivro = new javax.swing.JTextField();
        nomeLeitorLabel = new javax.swing.JLabel();
        nomeLeitor = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo.setText("Pesquisa Avançada");

        tituloLivroLabel.setText("Título do Livro");

        nomeLeitorLabel.setText("Nome do Leitor");

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloLivro)
                    .addComponent(nomeLeitor)
                    .addComponent(titulo)
                    .addComponent(tituloLivroLabel)
                    .addComponent(nomeLeitorLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloLivroLabel)
                .addGap(5, 5, 5)
                .addComponent(tituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeLeitorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Limpa a pesquisa
     */
    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        tituloLivro.setText("");
        nomeLeitor.setText("");
        this.filtro = new EmprestimoFiltro();
        events.emit();
    }//GEN-LAST:event_limparActionPerformed

    /**
     * Executa a pesquisa
     */
    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        EmprestimoFiltro filtro = new EmprestimoFiltro();

        String nomeLivroText = tituloLivro.getText().trim();
        String nomeLeitorText = nomeLeitor.getText().trim();

        if (!nomeLivroText.equals("")) {
            filtro.porNomeLivro(nomeLivroText);
        }

        if (!nomeLeitorText.equals("")) {
            filtro.porNomeUsuario(nomeLeitorText);
        }

        this.filtro = filtro;
        events.emit();
    }//GEN-LAST:event_pesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nomeLeitor;
    private javax.swing.JLabel nomeLeitorLabel;
    private javax.swing.JButton pesquisar;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField tituloLivro;
    private javax.swing.JLabel tituloLivroLabel;
    // End of variables declaration//GEN-END:variables
}
