package br.edu.ifpb.gestaobibliotecadigital.views.reservas;

import br.edu.ifpb.gestaobibliotecadigital.models.emprestimos.Reserva;
import br.edu.ifpb.gestaobibliotecadigital.utils.Formatter;

public class DetalhesReserva extends javax.swing.JPanel {

    private Reserva reserva;

    public DetalhesReserva() {
        initComponents();
        setReserva(null);
    }

    /**
     * Atualiza a reserva selecionada
     */
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;

        if (reserva == null) {
            status.setText("Selecione uma Reserva...");
            dataReserva.setText(" ");
            dataExpiracao.setText(" ");
            dataEncerrada.setText(" ");
            emprestimoRealizado.setText(" ");
            return;
        }

        if (reserva.expirada()) {
            status.setText("Reserva Expirada");
        } else if (reserva.encerrada()) {
            status.setText("Reserva Encerrada");
        } else {
            status.setText("Reserva Aberta");
        }

        dataReserva.setText(Formatter.of(reserva.getDataReserva()).toString());
        dataExpiracao.setText(reserva.getDataExpiracao() == null ? "Não" : Formatter.of(reserva.getDataExpiracao()).toString());
        dataEncerrada.setText(reserva.getDataEncerrada() == null ? "Não" : Formatter.of(reserva.getDataEncerrada()).toString());
        emprestimoRealizado.setText(reserva.getEmprestimo() == null ? "Não" : "Sim");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detalhesEmprestimo = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        dataReservaLabel = new javax.swing.JLabel();
        dataExpiracaoLabel = new javax.swing.JLabel();
        dataEncerradaLabel = new javax.swing.JLabel();
        emprestimoRealizadoLabel = new javax.swing.JLabel();
        dataReserva = new javax.swing.JLabel();
        dataExpiracao = new javax.swing.JLabel();
        dataEncerrada = new javax.swing.JLabel();
        emprestimoRealizado = new javax.swing.JLabel();

        detalhesEmprestimo.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes da Reserva"));

        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status.setText("Status da Reserva");

        dataReservaLabel.setText("Data da reserva:");

        dataExpiracaoLabel.setText("Data de expiração:");

        dataEncerradaLabel.setText("Data encerrada:");

        emprestimoRealizadoLabel.setText("Empréstimo realizado:");

        dataReserva.setText("00/00/00 00:00:00");

        dataExpiracao.setText("00/00/00 00:00:00");

        dataEncerrada.setText("00/00/00 00:00:00");

        emprestimoRealizado.setText("Não");

        javax.swing.GroupLayout detalhesEmprestimoLayout = new javax.swing.GroupLayout(detalhesEmprestimo);
        detalhesEmprestimo.setLayout(detalhesEmprestimoLayout);
        detalhesEmprestimoLayout.setHorizontalGroup(
            detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataReservaLabel)
                            .addComponent(dataExpiracaoLabel)
                            .addComponent(dataEncerradaLabel)
                            .addComponent(emprestimoRealizadoLabel))
                        .addGap(12, 12, 12)
                        .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataExpiracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                            .addComponent(emprestimoRealizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataEncerrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        detalhesEmprestimoLayout.setVerticalGroup(
            detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesEmprestimoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataReservaLabel)
                    .addComponent(dataReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataExpiracaoLabel)
                    .addComponent(dataExpiracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataEncerradaLabel)
                    .addComponent(dataEncerrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emprestimoRealizadoLabel)
                    .addComponent(emprestimoRealizado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detalhesEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detalhesEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataEncerrada;
    private javax.swing.JLabel dataEncerradaLabel;
    private javax.swing.JLabel dataExpiracao;
    private javax.swing.JLabel dataExpiracaoLabel;
    private javax.swing.JLabel dataReserva;
    private javax.swing.JLabel dataReservaLabel;
    private javax.swing.JPanel detalhesEmprestimo;
    private javax.swing.JLabel emprestimoRealizado;
    private javax.swing.JLabel emprestimoRealizadoLabel;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
