package br.edu.ifpb.gestaobibliotecadigital.views.livros;

import br.edu.ifpb.gestaobibliotecadigital.models.livros.Livro;

public class DetalhesLivro extends javax.swing.JPanel {

    private Livro livro;

    public DetalhesLivro() {
        initComponents();
        setLivro(null);
    }

    /**
     * Atualiza o livro selecionado
     */
    public void setLivro(Livro livro) {
        this.livro = livro;

        if (livro == null) {
            nomeLivro.setText(" ");
        } else {
            nomeLivro.setText(livro.getTitulo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        livroBorder = new javax.swing.JPanel();
        nomeLivro = new javax.swing.JLabel();

        livroBorder.setBorder(javax.swing.BorderFactory.createTitledBorder("Livro"));

        nomeLivro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeLivro.setText("Nome do Livro");

        javax.swing.GroupLayout livroBorderLayout = new javax.swing.GroupLayout(livroBorder);
        livroBorder.setLayout(livroBorderLayout);
        livroBorderLayout.setHorizontalGroup(
            livroBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livroBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );
        livroBorderLayout.setVerticalGroup(
            livroBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livroBorderLayout.createSequentialGroup()
                .addComponent(nomeLivro)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(livroBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(livroBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel livroBorder;
    private javax.swing.JLabel nomeLivro;
    // End of variables declaration//GEN-END:variables

}
