package br.edu.ifpb.gestaobibliotecadigital.views.livros;

import br.edu.ifpb.gestaobibliotecadigital.models.livros.Livro;

public class SinopseLivro extends javax.swing.JPanel {

    private Livro livro;

    public SinopseLivro() {
        initComponents();
        setLivro(null);
    }

    /**
     * Atualiza a sinopse do livro selecionado
     */
    void setLivro(Livro livro) {
        
        this.livro = livro;

        if (livro == null) {
            sinopseLivro.setText(" ");
        } else {
            System.out.print(livro.getSinopse());
            sinopseLivro.setText(livro.getSinopse());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sinopseBorder = new javax.swing.JPanel();
        sinopseLivro = new javax.swing.JLabel();

        sinopseBorder.setBorder(javax.swing.BorderFactory.createTitledBorder("Livro"));

        sinopseLivro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinopseLivro.setText("Sinpose");

        javax.swing.GroupLayout sinopseBorderLayout = new javax.swing.GroupLayout(sinopseBorder);
        sinopseBorder.setLayout(sinopseBorderLayout);
        sinopseBorderLayout.setHorizontalGroup(
            sinopseBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sinopseBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sinopseLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );
        sinopseBorderLayout.setVerticalGroup(
            sinopseBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sinopseBorderLayout.createSequentialGroup()
                .addComponent(sinopseLivro)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sinopseBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sinopseBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel sinopseBorder;
    private javax.swing.JLabel sinopseLivro;
    // End of variables declaration//GEN-END:variables

}
